version: '3.8'

services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    depends_on:
      - database
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DATABASE_NAME=dbname
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=pass
      - DATABASE_HOST=localhost

  database:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    ports:
       - "5433:5432"