version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8015:8000"
    restart: always
    environment:
      - DB_HOST=localhost
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5433

    command: sh -c "python manage.py runserver 0.0.0.0:8000"

  database:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5433